project:
  type: book
  output-dir: docs

book:
  title: "Python for Data Analysis Book Club"
  subtitle: "The R4DS Online Learning Community"
  logo: cover.png
  site-url: https://wesmckinney.com/book/
  repo-url: https://github.com/r4ds/bookclub-py4da
  sharing: [twitter, facebook, linkedin]
  page-footer:
    right: "1850 depiction of Ptilocercus lowii"
  number-depth: 0
  toc-depth: 0

  chapters:
    - index.qmd
    - part: Chapter01.ipynb

format:
  html:
    theme: cosmo
    fontsize: 16pt

execute:
  freeze: auto
